Mobile _first
Eccb7/My-Portfolio pull request #3
Opened 2023-04-27 17:37 UTC by Eccb7

This is a pull request with the updated changes based on the linters errors that were in the previous. It has been updated and no found errors. The project being reviewed is all about the mobile view approach of my portfolio website which would later help me understand the responsiveness of websites.

2023-04-27 19:12 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @Eccb7  
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Linters are green
 
 ## Required Changes 

- [ ] Check under the review 

 ## Optional suggestions 

-[ ]N/A

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 19:12 UTC, Alfredbis29 commented on index.html
> +            <div class="humburger">
- [ ] The nice design thus far, but there is still a need for improvement to make it look more professional. Please raise the size of your hamburger menu to fit the Figma design; see the difference below and adjust it.
Your Design  :wink: 
![Screenshot from 2023-04-27 20-27-19](https://user-images.githubusercontent.com/88894525/234959120-b19f056b-d0ec-4889-993a-9c7393a96d80.png)



Figma Design
![Screenshot from 2023-04-27 20-26-46](https://user-images.githubusercontent.com/88894525/234958873-f15c8f44-f6ce-42b1-a486-66fe68b1f5f8.png)

2023-04-27 19:12 UTC, Alfredbis29 commented on style.css
> +}
- [ ]You did a fantastic job on this project, but there are still a few minor things that need to be fixed for it to look awesome. Since we are imitating the Figma design, and if we compare your design and the original look are different, please fix your `background image` to match the Figma design. This will make your application look appealing. please fix this :point_down: 
Figma Design 
![Screenshot from 2023-04-27 20-25-44](https://user-images.githubusercontent.com/88894525/234961404-036a6f7a-091e-44ea-b09c-54471ab25e03.png)

Your Design
![Screenshot from 2023-04-27 20-39-03](https://user-images.githubusercontent.com/88894525/234961530-6c593132-8067-400d-b69a-2435cf2a17c0.png)

2023-04-27 19:12 UTC, Alfredbis29 commented on index.html
> +            <ul class="socials">
- [ ] I noticed that your paragraph didn't reflect the figma design paragraph , and aslo the `LET'S CONNECT` should be in uppercase , kindly fix this to reflect the original design 
Your design
![Screenshot from 2023-04-27 20-54-36](https://user-images.githubusercontent.com/88894525/234965457-1813745e-1a9c-485b-be15-8f59faffa410.png)

Figma design 
![Screenshot from 2023-04-27 20-58-20](https://user-images.githubusercontent.com/88894525/234965654-5e049adf-07ca-4def-97b5-34ec84bdd37e.png)

2023-04-27 23:00 UTC, Kamba56 requested changes
Hi @Eccb7, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great job using flexbox to layout contents of your page!👏👏👏
-!👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 23:00 UTC, Kamba56 commented on index.html
- [Optional] Kindly consider using an indentation of two spaces in all your documents. THis is a convention and also best practices.

2023-04-27 23:00 UTC, Kamba56 commented on index.html
> +                </div>
- [Optional] Kindly use a button or an `a` tag to wrap the hamburger icon. The hamburger is a button that when clicked, it displays the mobile nav. It is best for html5 semantics to use a button tag for every button.

2023-04-27 23:00 UTC, Kamba56 commented on style.css
> +
- [ ] Kindly remove all commented pieces of code from all your documents. This is to keep your documents clean and professional.

2023-04-27 23:16 UTC, Eccb7 commented on index.html
> +                </div>
Hello @Kamba56 Hope you well
I've tried but been experiencing challenges with the hamburger, thought of implementing media queries but I feel I'll have that later in the projects for its full responsiveness

2023-04-28 00:32 UTC, Efiamotu-1 approved these changes
Hi @Eccb7 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 00:32 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] From the figma design attached below you are missing a social media icon which should be that of `medium` kindly please add this icon to your project as doing this would match the figma template and show that you are a developer who pays attention to details. :+1:

2023-04-28 00:32 UTC, Efiamotu-1 commented on style.css
[OPTIONAL] 
* [ ]  It is noticed that `display: flex` property is repeated multiple times, Kindly let us stick to the DRY principle by not repeating a property more than it should slightly_smiling_face. This can be done by having a class called `.flex-row` or `.flex-column` and assigning it wherever possible as a class name in your `html` markup code.
 
 ```
 .flex-row {
   display: flex;
 }
 
 .flex-column {
   display: flex;
   flex-direction: column;
 }
 ```
 
 * And kindly attend to any repetitions in your code :slightly_smiling_face:

2023-04-28 00:32 UTC, Efiamotu-1 commented on README.md
[OPTIONAL]
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)

2023-04-28 00:32 UTC, Efiamotu-1 commented on README.md
> +```
- [ ] Kindly customise this section correctly as well to make your project look more professional. this is an [example template](https://github.com/rychrr/portofolio_page/blob/main/README.md) you can use to set up this section :+1: 
[OPTIONAL]
- [ ] you also missed some sections and its descriptions which the initial reviewers should have flagged, check this  [example template](https://github.com/rychrr/portofolio_page/blob/main/README.md) and fix them accordingly :+1:

2023-04-28 06:18 UTC, Kamba56 commented on index.html
> +                </div>
> Hello @Kamba56 Hope you well I've tried but been experiencing challenges with the hamburger, thought of implementing media queries but I feel I'll have that later in the projects for its full responsiveness

Hello. Please I am not saying you should implement the functionality of the button. You will do that in future projects. I am just saying you should wrap it in a button element.

2023-04-28 13:24 UTC, merged